apiVersion: autoscaling.x-k8s.io/v1alpha1
kind: StartupCPUBoost
metadata:
  name: boost-001
selector:
  matchExpressions:
  - key: app.kubernetes.io/name
    operator: In
    values: ["frontend"]
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: hotel-reserv-frontend
      fixedResources:
        requests: "1430m"
        limits: "2"
  durationPolicy:
    fixedDuration:
      unit: Seconds
      value: 120
